services:
  dc:
    image: kasmweb/discord:1.18.0-rolling-weekly
    pull_policy: daily
    tty: true
    stdin_open: true
    environment: 
     VNC_PW: "password"
    ports: 
     - "6901:6901"